name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build, Test, and Generate JaCoCo Badge

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build, Test, and Build Docker Image
        run: |
          export SHELL=/bin/bash
          ./gradlew clean build test   # Gradle build et test

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
